geometry_msgs/PoseStamped target_pose
float64 std_x
float64 std_y
float64 std_w
uint64 max_samples

# Speed limits. Will not exceed global limits.
float64 max_velocity_x       # (m/s) Default: 0.2
float64 max_velocity_y       # (m/s) Default: 0.2
float64 max_velocity_w       # (rad/s) Default: 0.2

float64 xy_goal_tolerance    # (m) Default: 0.02
float64 yaw_goal_tolerance   # (rad) Default: 0.01

float64 avoid_distance       # Obstacle avoid distance (m), default: 0.0

# If zero, default will be used
float64 backwards_mult       # Cost multiplier for reversing, default: 1.5
float64 strafe_mult          # Cost multiplier for strafing, default: 1.5
float64 rotation_mult        # Cost multiplier for in-place rotation, default: 0.3/PI
---
---
uint8 state

uint8 UNKNOWN=0
uint8 NO_PLAN=1
uint8 GOOD_PLAN=2
uint8 STUCK=3
uint8 COLLISION=4